<?php
/**
 * This file is part of Codelegacy_InstanceReminder for Magento.
 *
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author Alex P <alexander@codelegacy> <Codelegacy>
 * @category Codelegacy
 * @package Codelegacy_InstanceReminder
 */
?>
<?php /** @var Mage_Adminhtml_Block_Template $this */ ?>
<?php
/** @var Codelegacy_InstanceReminder_Helper_Data $_helper */
$_helper = Mage::helper('codelegacy_instancereminder');
?>
<?php if ($_helper->isEnabled()) : ?>
    <?php if ($_helper->isAdminLoginPage()): ?>
        <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('codelegacy/instancereminder/topbar.css') ?>" media="all"/>
    <?php endif; ?>
    <style>
        #codelegacy_ir {
            background: <?php echo $_helper->getColorByInstance() ?>;
        }
    </style>
    <div id="codelegacy_ir">
        <img id="codelegacy_ir_logo" src="<?php echo $this->getSkinUrl('images/codelegacy/logo.png') ?>" alt="Codelegacy">
        <span><?php echo $_helper->getInstanceName() ?></span>
    </div>
<?php endif; ?>